// <auto-generated />
using System;
using Linewise.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Linewise.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LinewiseDbContext))]
    [Migration("20260818172916_LineDetails")]
    partial class LineDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Linewise.Domain.Auditing.AuditEntry", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Sequence");

                    b.HasIndex("PreviousHash")
                        .IsUnique();

                    b.ToTable("AuditEntries", (string)null);
                });

            modelBuilder.Entity("Linewise.Domain.Entities.Assignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LineId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RosterVersionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RosterVersionId");

                    b.ToTable("Assignments", (string)null);
                });

            modelBuilder.Entity("Linewise.Domain.Entities.Availability", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("EmployeeId", "Date");

                    b.HasIndex("Date");

                    b.HasIndex("Date", "Source");

                    b.ToTable("Availabilities", (string)null);
                });

            modelBuilder.Entity("Linewise.Domain.Entities.CommittedImport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndDateExclusive")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FirstDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ImportTemplateId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImportedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("RowsImported")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowsResolvedManually")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImportedAtUtc");

                    b.ToTable("CommittedImports", (string)null);
                });

            modelBuilder.Entity("Linewise.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTemporary")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("Linewise.Domain.Entities.ImportTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateFormat")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("EmptyCellStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FirstDateColumnIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeaderRowIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("NameColumnIndex")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReportUnrecognisedCells")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorksheetName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ImportTemplates", (string)null);
                });

            modelBuilder.Entity("Linewise.Domain.Entities.LeaderEligibility", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LineId")
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId", "LineId");

                    b.ToTable("LeaderEligibilities", (string)null);
                });

            modelBuilder.Entity("Linewise.Domain.Entities.LineDemand", b =>
                {
                    b.Property<Guid>("LineId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequiredHeadcount")
                        .HasColumnType("INTEGER");

                    b.HasKey("LineId", "Date");

                    b.HasIndex("Date");

                    b.ToTable("LineDemands", (string)null);
                });

            modelBuilder.Entity("Linewise.Domain.Entities.LinePreference", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LineId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("EmployeeId", "LineId");

                    b.ToTable("LinePreferences", (string)null);
                });

            modelBuilder.Entity("Linewise.Domain.Entities.OperatingAssistantEligibility", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LineId")
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId", "LineId");

                    b.ToTable("OperatingAssistantEligibilities", (string)null);
                });

            modelBuilder.Entity("Linewise.Domain.Entities.PrintSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BaseFontPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("LogoPng")
                        .HasColumnType("BLOB");

                    b.Property<int>("Orientation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaperSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseAccentColours")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PrintSettings", (string)null);
                });

            modelBuilder.Entity("Linewise.Domain.Entities.ProductionLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccentColour")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LayoutNotes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("RequiredHeadcount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequiredOperatingAssistants")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Lines", (string)null);
                });

            modelBuilder.Entity("Linewise.Domain.Entities.RosterVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WeekStart", "VersionNumber")
                        .IsUnique();

                    b.ToTable("RosterVersions", (string)null);
                });

            modelBuilder.Entity("Linewise.Domain.Entities.Shift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Name")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Date", "Name")
                        .IsUnique();

                    b.ToTable("Shifts", (string)null);
                });

            modelBuilder.Entity("Linewise.Domain.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Skills", (string)null);
                });

            modelBuilder.Entity("Linewise.Domain.Rostering.RosterWarning", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Code")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LineId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RosterVersionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RosterVersionId");

                    b.ToTable("RosterWarnings", (string)null);
                });

            modelBuilder.Entity("Linewise.Infrastructure.Persistence.EmployeeAliasRow", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Alias")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId", "Alias");

                    b.ToTable("EmployeeAliases", (string)null);
                });

            modelBuilder.Entity("Linewise.Infrastructure.Persistence.EmployeeSkillRow", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId", "SkillId");

                    b.ToTable("EmployeeSkills", (string)null);
                });

            modelBuilder.Entity("Linewise.Infrastructure.Persistence.ImportFileRow", b =>
                {
                    b.Property<Guid>("CommittedImportId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("CommittedImportId");

                    b.ToTable("ImportFiles", (string)null);
                });

            modelBuilder.Entity("Linewise.Infrastructure.Persistence.ImportTemplateRuleRow", b =>
                {
                    b.Property<Guid>("ImportTemplateId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ImportTemplateId", "Ordinal");

                    b.ToTable("ImportTemplateRules", (string)null);
                });

            modelBuilder.Entity("Linewise.Infrastructure.Persistence.LineSkillRow", b =>
                {
                    b.Property<Guid>("LineId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("TEXT");

                    b.HasKey("LineId", "SkillId");

                    b.ToTable("LineRequiredSkills", (string)null);
                });

            modelBuilder.Entity("Linewise.Infrastructure.Persistence.RosterDayRow", b =>
                {
                    b.Property<Guid>("RosterVersionId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.HasKey("RosterVersionId", "Date", "ShiftId");

                    b.ToTable("RosterDays", (string)null);
                });

            modelBuilder.Entity("Linewise.Domain.Entities.Assignment", b =>
                {
                    b.HasOne("Linewise.Domain.Entities.RosterVersion", null)
                        .WithMany()
                        .HasForeignKey("RosterVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Linewise.Domain.Rostering.AssignmentExplanation", "Explanation", b1 =>
                        {
                            b1.Property<long>("AssignmentId")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("PreferenceRank")
                                .HasColumnType("INTEGER")
                                .HasColumnName("PreferenceRank");

                            b1.Property<int>("Rule")
                                .HasColumnType("INTEGER")
                                .HasColumnName("PlacementRule");

                            b1.HasKey("AssignmentId");

                            b1.ToTable("Assignments");

                            b1.WithOwner()
                                .HasForeignKey("AssignmentId");
                        });

                    b.Navigation("Explanation")
                        .IsRequired();
                });

            modelBuilder.Entity("Linewise.Domain.Entities.LineDemand", b =>
                {
                    b.HasOne("Linewise.Domain.Entities.ProductionLine", null)
                        .WithMany()
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Linewise.Domain.Rostering.RosterWarning", b =>
                {
                    b.HasOne("Linewise.Domain.Entities.RosterVersion", null)
                        .WithMany()
                        .HasForeignKey("RosterVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Linewise.Infrastructure.Persistence.ImportFileRow", b =>
                {
                    b.HasOne("Linewise.Domain.Entities.CommittedImport", null)
                        .WithMany()
                        .HasForeignKey("CommittedImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Linewise.Infrastructure.Persistence.ImportTemplateRuleRow", b =>
                {
                    b.HasOne("Linewise.Domain.Entities.ImportTemplate", null)
                        .WithMany()
                        .HasForeignKey("ImportTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Linewise.Infrastructure.Persistence.RosterDayRow", b =>
                {
                    b.HasOne("Linewise.Domain.Entities.RosterVersion", null)
                        .WithMany()
                        .HasForeignKey("RosterVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
